# Generated by Django 4.2 on 2023-04-21 22:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpRequest',
            fields=[
                ('requset_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('phone', 'Phone'), ('e-mail', 'Email')], default='phone', max_length=10)),
                ('reciever', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=4)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
