# Generated by Django 4.2 on 2023-04-21 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_otprequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otprequest',
            old_name='requset_id',
            new_name='request_id',
        ),
    ]
