# Generated by Django 4.2 on 2023-04-21 23:06

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_requset_id_otprequest_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprequest',
            name='password',
            field=models.CharField(default=users.models.generate_otp, max_length=4),
        ),
    ]
