# Generated by Django 4.2 on 2023-05-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userverify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverify',
            name='active_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userverify',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userverify',
            name='phone',
            field=models.TextField(blank=True, max_length=20),
        ),
    ]
